### ISSUE TITLE
pxatbegshi と multicol の共存

### ISSUE THREAD

**Issue by doraTeX** [aminophen/platex-tools#13]
TeX Live 2019 での縦組時，`multicol` パッケージと `pxatbegshi` パッケージが共存できなくなっているようです。
次のソースは，`pxatbegshi` パッケージを v0.3 に戻すとコンパイルが通りますが，v0.4 だとエラーとなります。

# サンプルソース
```tex
%!platex
\documentclass{tarticle}
\usepackage{multicol}
\usepackage{pxatbegshi}

\begin{document}
\begin{multicols*}{2}
\makeatletter
\@tempcnta\z@
\loop
あ
\advance\@tempcnta\@ne
\ifnum\@tempcnta<2000\repeat
\end{multicols*}
\end{document}
```

# TeX Live 2019 でのエラー

```tex
! Use `\yoko' at top of list.
\pxabgs@ABS@prehook ->\iftdir \yoko 
                                    \let \pxabgs@restore@dir \tate \else \le...
l.13 \end{multicols*}
```

**Comment by aminophen** [comment]
報告ありがとうございます。再現しました。挙動の v0.3 → v0.4 での変化は

* v0.3 までは北川さんのコードをベースにしていた。
* しかし，以下の理由で v0.4 からは bxpapersize のコードに合わせた。
    * \AtBeginShipoutDiscard な場合がうまくいかなかった
    * ZR さんの bxpapersize も atbegshi にパッチするので，衝突しないようにしたい

という理由です。というわけで，以下のコードでも同じエラーを起こせますね。

``` tex
\documentclass[b5paper]{tarticle}
\usepackage{multicol}
\usepackage[priority=high]{bxpapersize}

\begin{document}
\begin{multicols*}{2}
\makeatletter
\@tempcnta\z@
\loop
あ
\advance\@tempcnta\@ne
\ifnum\@tempcnta<2000\repeat
\end{multicols*}
\end{document}
```

**Comment by aminophen** [comment]
bxpapersize.sty の中に

```
% In (u)pTeX engine, boxes and lists have the direction attribute,
% and yoko boxes cannot be unboxed in tate lists (and vice versa).
% This restriction can cause the atbegshi package to fail, and thus
% the 'priority=low' setting results in an error when used together
% with document classes of tate direction.
```

というコメントを見つけました。しかし，実際には `priority=low` と `priority=high` でもエラーになっています（`priority=middle` は atbegshi にパッチしないのでセーフ）。

もう少し詳しく調べてみます。

**Comment by aminophen** [comment]
e5252b3 で元のコードに戻し，platex-tools 2019-09-07 として出しました。\AtBeginShipoutDiscard 対策もうまくいっているようなので…

ですが，まだ multicol でエラーが出る詳細な理由はわかっていないのと，bxpapersize の方にも報告して良いのではと思ったので，もうしばらく考えるために issue は閉じずにおきます。

**Comment by aminophen** [comment]
bxpapersize が pxatbegshi へ丸投げしてきたので，エラーは無くなりましたので閉じます。
