### ISSUE TITLE
pxatbegshi をロードすると \AtBeginShipOut で指定した内容が出力されない

### ISSUE THREAD

**Issue by h-kitagawa** [aminophen/platex-tools#15]
LaTeX 2020-10-01 対応でいろいろ試しているついでに見つけました．
次のソースで ```\usepackage{pxatbegshi}``` のコメントアウトを外すと，（2 ページ目以降で）基本版面上部の赤字「ほーげー」が出力されなくなります．
```tex
\documentclass{article}
%\usepackage{pxatbegshi} <==
\usepackage{atbegshi}\AtBeginShipoutInit
\usepackage{bxjalipsum,xcolor}
\AtBeginShipout{\smash{\color{red}\huge\gtfamily ほーげー}}
\begin{document}
\jalipsum[1-20]{wagahai}
\end{document}
```

**Comment by h-kitagawa** [comment]
自己レスです．pxatbegshi 非読み込み時には，

> ```\AtBeginShipout{\smash{\color{red}\huge\gtfamily ほーげー}}```

の引数 ```\smash{\color{red}\huge\gtfamily ほーげー}}``` 自体は外部垂直モードで実行されるため，「ほーげー」が次ページの先頭になっていたようです．
しかし pxatbegshi 読み込み時では同じ内容が ```\setbox8=\vbox{...}``` の内部で実行されるため，この ```\box8``` の内部で完結してしまったというわけです（LuaTeX-ja の lltjp-atbegshi.sty なども同じ）．

ただ，こういう ```\AtBeginShipout``` の使い方は想定されているのでしょうかは疑問です．

**Comment by aminophen** [comment]
そもそも pxatbegshi の方針が妥当なのか？というのはさいけんとうがひつようかもしれません。このテストケースにおいては，tarticle に変えてもなお「pxatbegshi なし」でエラーなく通ります。pxatbegshi が必要なケース（Incompatible direction ... エラー）と必要でないケースを考え直そうかと思います。

**Comment by h-kitagawa** [comment]
> pxatbegshi が必要なケース（Incompatible direction ... エラー）

とりあえず，次の (1)--(4) があります．それ以外にも，\AtBeginShipout 内で unbox  している場合を排除できないので，やっぱり hook を横組で実行させないと安全ではない気がします．

```tex
\documentclass{tarticle}
\makeatletter
\expandafter\newif\csname ifltj@ltfilehook@avail\endcsname
\@ifl@t@r\fmtversion{2020-10-01}{%
  \ifnum\patch@level<0\relax \ifnum\patch@level<-6 \ltj@ltfilehook@availtrue\fi
  \else\ltj@ltfilehook@availtrue\fi
}{}
\ifltj@ltfilehook@avail\else
  \RequirePackage{atbegshi}\AtBeginShipoutInit
\fi
%\AtBeginShipout{\AtBeginShipoutAddToBox{VA}}          % (1)
%\AtBeginShipout{\AtBeginShipoutAddToBoxForeground{VA}}% (2)
%\AtBeginShipout{%                                       (3)
%  \AtBeginShipoutUpperLeft{\put(20,-20){HOGE}}%
%}
%\AtBeginShipout{%                                       (4)
%  \AtBeginShipoutUpperLeftForeground{\put(20,-20){HOGE}}%
%}

\begin{document}
◆
\end{document}
```

(8/06 10:51 edit) 上の 4 ケースだけ対応というのなら，`\AtBeginShipoutAddToBox` 等で unbox しないように書き換えればいいのかもしれません．

**Comment by aminophen** [comment]
> pxatbegshi 読み込み時では同じ内容が `\setbox8=\vbox{...}` の内部で実行される

この件について思ったのですが，現行の pxatbegshi のような大胆なことをしなくても単に

``` tex
\AtBeginDocument{\AtBeginShipout{\yoko}}
```

だけで動くことが多いような気がします。例示していただいた(1)--(4)はいずれも

``` tex
\documentclass{tarticle}
\usepackage{atbegshi}% contains \AtBeginDocument{\AtBeginShipoutInit}
\AtBeginDocument{\AtBeginShipout{\yoko}}
%%% 以下同文
```

で動いているように見えます。全体を \yoko な \vbox で実行する意味があったのだろうか…？

[edit] 安全ではないらしい。

> \DeclareHookRule でフック間に実行順序を付けられることが不安です．例えば
> \AddToHook{shipout/before}[platex]{\yoko} % platex format で指定を想定
> \AddToHook{shipout/before}[test]{\hbox{え}}
> \DeclareHookRule{shipout/before}{platex}{after}{test}
> とすると ! Use '\yoko' at top of list. エラーです．

**Comment by aminophen** [comment]
https://github.com/texjporg/tests-shipout/issues/1#issuecomment-698907347

のとおり，実装上の都合で pLaTeX2e 2020-10-01 では「縦組クラスでは『`\AtBeginShipout` の中身が外部垂直モードで実行されること』を想定した使用はサポートしない」と明記しようと思います。

pxatbegshi の方は

* LaTeX2e 2020-10-01 以降では「pxatbegshi は何もしない」。
  - pLaTeX2e 2020-10-01 でカーネル側が対処する前提。
* 従来の LaTeX2e では「pxatbegshi は常に横組ボックスに入れて実行」。
  - 今の時点で「横組なら敢えてボックスに入れない」を実装し直す意義は小さいと思うので。

として，ドキュメント化しました (e57fd01)。
