### ISSUE TITLE
plarray ロード時の \hspace

### ISSUE THREAD

**Issue by doraTeX** [aminophen/platex-tools#7]
plarray の仕様上仕方ないことかもしれませんが，plarray をロードすると `\hspace` のセル幅が潰されますね。
`\hspace` でセル幅を確保して見栄えを調整していた表組の組版結果が変わってしまうので，要注意となります。

# 何もロードしない場合
```tex
%!platex
\documentclass{article}
\begin{document}
\begin{tabular}{|c|}
\hspace{5cm}
\end{tabular}
\end{document}
```
<img width="278" alt="2017-12-22 13 17 54" src="https://user-images.githubusercontent.com/6186180/34285134-9e68fad6-e71a-11e7-8be2-44a741baeace.png">

# arrayパッケージをロードした場合
```tex
%!platex
\documentclass{article}
\usepackage{array}
\begin{document}
\begin{tabular}{|c|}
\hspace{5cm}
\end{tabular}
\end{document}
```

<img width="278" alt="2017-12-22 13 17 54" src="https://user-images.githubusercontent.com/6186180/34285134-9e68fad6-e71a-11e7-8be2-44a741baeace.png">

# plarrayパッケージをロードした場合
```tex
%!platex
\documentclass{article}
\usepackage{plarray}
\begin{document}
\begin{tabular}{|c|}
\hspace{5cm}
\end{tabular}
\end{document}
```
<img width="91" alt="2017-12-22 13 19 07" src="https://user-images.githubusercontent.com/6186180/34285144-b82fa4d8-e71a-11e7-99df-ddc23ea38c28.png">

**Comment by aminophen** [comment]
array パッケージを読むのであれば，セル幅固定は `m{5cm}` でやればいいんじゃないかという感じはしますが，対処できるかどうか一応考えてみます。

**Comment by aminophen** [comment]
以下のソースの結果を見る限り，そもそも \hspace{5cm} というセル要素は LaTeX もサポート外なのではないでしょうか？

~~~~ tex
%#!pdflatex
\documentclass{article}
\begin{document}

[1]
\begin{tabular}{|c|}
\hspace{5cm}
\end{tabular}

[2]
\begin{tabular}{|c|}
\hspace{5cm}\\
A
\end{tabular}

[3]
\begin{tabular}{|c|}
A\\
\hspace{5cm}
\end{tabular}

\end{document}
~~~~

<img width="593" alt="tabular-hspace" src="https://user-images.githubusercontent.com/9957466/34296778-a1f184ba-e757-11e7-8129-60e0bcc124cf.png">

**Comment by doraTeX** [comment]
なるほど，こんな挙動があったとは……
それなら確かにそもそも latex.ltx 側で対処すべき項目ということで，ひとまずサポート外ということでもいいと思います。

**Comment by aminophen** [comment]
[2] については「`\\` の前にスペースを置くかどうか」で結果が変わります。

~~~~ tex
\documentclass{article}
\begin{document}

[2]
\begin{tabular}{|c|}
\hspace{5cm}\\
A
\end{tabular}

[2']
\begin{tabular}{|c|}
\hspace{5cm} \\
A
\end{tabular}

\end{document}
~~~~

釈迦に説法な気がしますが，これは `\@tabclassz` の \unskip が「`\\` 直前の空白文字が挿入するスペース」と「`\hspace{5cm}`」のどちらを消すか，ということです。

**Comment by aminophen** [comment]
ちなみに [2] については「`\\` の前にスペースを置くかどうか」で結果が変わります。

~~~~ tex
\documentclass{article}
\begin{document}

[2]
\begin{tabular}{|c|}
\hspace{5cm}\\
A
\end{tabular}

[2']
\begin{tabular}{|c|}
\hspace{5cm} \\
A
\end{tabular}

\end{document}
~~~~

<img width="603" alt="tabular-hspace-2" src="https://user-images.githubusercontent.com/9957466/34298544-a9da347e-e761-11e7-9689-c51705cc3461.png">

同様に [1] の方も \hspace{5cm} 直後に `%` でも置いて空白トークンをなくすと，スペースが食われます。釈迦に説法な気がしますが，これは `\@tabclassz` の \unskip が「`\\` 直前の空白文字が挿入するスペース」と「`\hspace{5cm}`」のどちらを消すか，ということです。

\unskip が何に効くかはなかなかに難しい問題なので，「\hspace したいのであれば，\null を挿入する」という使い方ではいかがでしょう？

**Comment by doraTeX** [comment]
> \unskip が何に効くかはなかなかに難しい問題なので，「\hspace したいのであれば，\null を挿入する」という使い方ではいかがでしょう？

はい，そんな感じの運用ということで問題ないと思います。

**Comment by aminophen** [comment]
> \unskip が何に効くかはなかなかに難しい問題

texjporg/tex-jp-build#52 で追加された \lastnodesubtype プリミティブを使うと，「最後のノードが JFM 由来のグルーの場合だけそれを \unskip する」という処理が可能になるため，これを pLaTeX カーネルに \removejfmglue という名前のマクロで導入しました (texjporg/platex#65) 。そして，それを plarray.sty で使うことで，本 issue を解決することができたと思います。e-pTeX 180226 以降が必要ですが，これは TeX Live 2018 pretest には既に適用されています。

**Comment by aminophen** [comment]
興味深いことに，本家 LaTeX2e でも昨日あたりから latex3/latex2e#23 という議論があって，これも tabular の \unskip が無限大のグルーを消してしまうことに関するものですね。
