### ISSUE TITLE
pxgentombow: トンボに表示するジョブ情報のカスタマイズ

### ISSUE THREAD

**Issue by wtsnjp** [aminophen/platex-tools#8]
(px)gentombow において，現状ではトンボに表示するジョブ情報は `<jobname> (yy-mm-dd HH:MM)` で固定されており，インターフェース的には `notombowdate` オプションによってその有無を指定することしかできません．

しかし，近年の TeX エンジンでは秒単位までの時刻取得が可能でありますし（特に非 px な gentombow の存在意義を考えると）地域によっては `yy-mm-dd` 以外の流儀を採用したい場合も考えられます．また，`<jobname>` と日付・時刻以外の情報を表示すると便利なこともあるかもしれません．

そうしたユースケースに柔軟に対応するため，トンボに表示するジョブ情報を柔軟にカスタマイズできるよ良さそうに思いました．実装を見る限りトークンレジスタ `\@bannertoken` へアクセスするインターフェースを用意するだけで実現できそうに思われますが，いかがでしょうか？

**Comment by aminophen** [comment]
一度は実装しようと思ったのですが，さぼっていました。

`\@bannertoken` を更新した後に `\maketombowbox` すればよく，インタフェース化はそう難しくないと思うので，時間があるときにやってみます。

**Comment by aminophen** [comment]
あと，`\@bannerfont` も変えられるとよいのかな（特にネイティブな Unicode フォントを使えるエンジンの場合）と思うので，その辺も要調整と思います。

**Comment by aminophen** [comment]
\settombowbanner という命令を追加してみました。以下のようなことができます。

~~~~ tex
%#!platex
\documentclass[a4paper]{book}
\usepackage{pxgentombow}
\usepackage{bounddvi}
\settombowbanner{\jobname\space (\pdfcreationdate)}
\begin{document}
トンボのテストです。
\end{document}
~~~~

ついでに微妙に合っていないと感じた `(no)tombowdate` というパッケージオプション名は obsolete 扱いにして，`(no)tombowbanner` にリネームします。ドキュメントはまだですが…。（互換性のため，`(no)tombowdate` は警告を出して `(no)tombowbanner` に渡ります）

追記： ace6e89 でドキュメント更新。

**Comment by aminophen** [comment]
https://github.com/aminophen/gentombow にリポジトリを移して独立させ，リリースしようと思います。
