### ISSUE TITLE
plarray ロード時の p 指定の tabular でのセル冒頭の \relax\par 

### ISSUE THREAD

**Issue by doraTeX** [aminophen/platex-tools#9]
[pLaTeX の #63](https://github.com/texjporg/platex/issues/63) と同様の問題が，plarray でも発生します。

```tex
\documentclass{article}
\usepackage{array}
\begin{document}
\begin{tabular}{p{5cm}}
A\\
\relax\par
A
\end{tabular}
\end{document}
```

このソースを pdfLaTeX で組版すると空行は空きませんが，`array` を `plarray` に変えて pLaTeX で組版すると空行が空きます。

**Comment by aminophen** [comment]
LaTeX カーネルでは l, c, r は `\@〜classz`，p は `\@classv` という別実装になっているのですが，array では両方とも `\insert@column` なので，これまた厄介です…

まだ試していませんが，北川さんのコードで追加された `\pltx@next@inhibitglue` を援用してみようと思います。が，以前の #7 と同じく「実装の都合上，完全互換にはならない」という制約はやっぱりどこかに残るかもしれませんね。（表組の中で \par を使う必要が生じる状況がどのくらいあるのか？）

**Comment by aminophen** [comment]
【 texjporg/platex#63 で議論中 】

**Comment by aminophen** [comment]
2018-03-16 リリースを以って #7 もろとも完了とします。
